# Generated by Django 4.2.9 on 2026-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': [models.OrderBy(models.F('published_at'), descending=True, nulls_last=True), '-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Set manually or auto-filled when publishing.', null=True),
        ),
    ]
