# Generated by Django 4.2.9 on 2026-05-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
