# Generated by Django 4.2.9 on 2026-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postcontent',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#2563EB', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
