# Generated by Django 4.2.9 on 2026-05-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
