# Generated by Django 4.2.9 on 2026-05-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
