# Generated by Django 4.2.9 on 2026-04-02 07:43

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or SVG string for frontend rendering.', max_length=100)),
                ('short_description', models.CharField(help_text='Shown on service cards.', max_length=300)),
                ('full_description', models.TextField(blank=True, help_text='Detailed description for the service detail page.')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.service_image_path)),
                ('features', models.TextField(blank=True, help_text='JSON list of feature bullet points.')),
                ('cta_text', models.CharField(default='Learn More', help_text='Call-to-action button label.', max_length=100)),
                ('cta_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
